# Generated by Django 3.2.2 on 2021-05-10 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counterapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='counter',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
